// Synchronizes the app's declared server capability revisions with `/meta`.
//
// Run from the repository root:
//   dart run buildtools/sync_server_capabilities.dart
//   dart run buildtools/sync_server_capabilities.dart --server-url https://example.com
//   dart run buildtools/sync_server_capabilities.dart --check
import 'dart:convert';
import 'dart:io';

const _defaultServerUrl = 'https://api.solian.app';
const _outputPath = 'lib/core/server_capabilities.g.dart';

Future<void> main(List<String> arguments) async {
  var serverUrl = _defaultServerUrl;
  var checkOnly = false;

  for (var index = 0; index < arguments.length; index++) {
    switch (arguments[index]) {
      case '--check':
        checkOnly = true;
        break;
      case '--server-url':
        if (index + 1 >= arguments.length) {
          usage('Missing value for --server-url.');
        }
        serverUrl = arguments[++index];
        break;
      case '--help' || '-h':
        stdout.writeln(
          'Usage: dart run buildtools/sync_server_capabilities.dart '
          '[--server-url <url>] [--check]',
        );
        return;
      default:
        usage('Unknown argument: ${arguments[index]}');
    }
  }

  final metadata = await _fetchMetadata(serverUrl);
  final contents = _renderCapabilities(metadata);
  final output = File(_outputPath);

  if (checkOnly) {
    if (!await output.exists() || await output.readAsString() != contents) {
      stderr.writeln('$_outputPath is out of date. Run the sync command.');
      exitCode = 1;
    }
    return;
  }

  await output.writeAsString(contents);
  stdout.writeln('Updated $_outputPath from $serverUrl/meta.');
}

Never usage(String message) {
  stderr.writeln(message);
  exitCode = 64;
  throw ArgumentError(message);
}

Future<Map<String, dynamic>> _fetchMetadata(String serverUrl) async {
  final baseUri = Uri.parse(
    serverUrl.endsWith('/') ? serverUrl : '$serverUrl/',
  );
  final client = HttpClient();
  try {
    final request = await client.getUrl(baseUri.resolve('meta'));
    final response = await request.close();
    final body = await utf8.decoder.bind(response).join();
    if (response.statusCode != HttpStatus.ok) {
      throw HttpException(
        'GET ${baseUri.resolve('meta')} returned '
        '${response.statusCode}: $body',
      );
    }
    final decoded = jsonDecode(body);
    if (decoded is! Map) {
      throw const FormatException('/meta did not return a JSON object.');
    }
    return Map<String, dynamic>.from(decoded);
  } finally {
    client.close(force: true);
  }
}

String _renderCapabilities(Map<String, dynamic> metadata) {
  final apiRevision = _readInt(metadata['api_revision']);
  final capabilities = metadata['capabilities'];
  if (apiRevision == null || capabilities is! Map) {
    throw const FormatException(
      '/meta is missing api_revision or capabilities.',
    );
  }

  final entries = <MapEntry<String, int>>[];
  for (final entry in capabilities.entries) {
    if (entry.key is! String || entry.value is! Map) continue;
    final revision = _readInt((entry.value as Map)['revision']);
    if (revision != null) entries.add(MapEntry(entry.key as String, revision));
  }
  if (entries.isEmpty) {
    throw const FormatException('/meta did not contain capability revisions.');
  }
  entries.sort((a, b) => a.key.compareTo(b.key));

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by buildtools/sync_server_capabilities.dart.')
    ..writeln()
    ..writeln('const kSupportedServerApiRevision = $apiRevision;')
    ..writeln()
    ..writeln('const kClientSupportedCapabilities = <String, int>{');
  for (final entry in entries) {
    buffer.writeln('  ${jsonEncode(entry.key)}: ${entry.value},');
  }
  buffer
    ..writeln('};')
    ..writeln();
  return buffer.toString();
}

int? _readInt(Object? value) => switch (value) {
  int value => value,
  num value => value.toInt(),
  _ => null,
};
